# 1. Download Helm 
- name: Download Helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755" 

# 2. Run Helm install Script
- name: Run Helm install script
  command: /tmp/get_helm.sh

# 3. Verify Helm is installed
- name: Verify Helm is installed
  command: helm version
  register: helm_version

- name: Show Helm version
  debug:
    msg: "{{ helm_version.stdout }}"