# 1. SYSTEM UPDATE
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

# 2. ADD CLUSTER HOSTS TO /etc/hosts
- name: Remove Vagrant loopback hostname entries
  lineinfile:
    path: "/etc/hosts"
    regexp: "^127\\.0\\..*\\s+{{ inventory_hostname }}$"
    state: absent

- name: Add cluster hosts to /etc/hosts
  become: true
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item.ip }} {{ item.host }}"
    state: present
  loop: "{{ k8s_nodes }}"