- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart nexus
  systemd:
    name: nexus
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted