#===============================================
#               K8S CLUSTER
#===============================================
[master]
k8s-master ansible_host=192.168.56.30 ansible_ssh_private_key_file=/home/vagrant/keys/k8s-master_key

[workers]
k8s-worker-1 ansible_host=192.168.56.31 ansible_ssh_private_key_file=/home/vagrant/keys/k8s-worker-1_key
k8s-worker-2 ansible_host=192.168.56.32 ansible_ssh_private_key_file=/home/vagrant/keys/k8s-worker-2_key

[k8s_cluster:children]
master
workers

#===============================================
#                   VM TOOLS 
#===============================================
[tools]
vm-tools ansible_host=192.168.56.33 ansible_ssh_private_key_file=/home/vagrant/keys/vm-tools_key

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/%(inventory_hostname)s/virtualbox/private_key # Which SSH key to use to connect to VM
ansible_ssh_common_args='-o StrictHostKeyChecking=no' # Do not verify the host to connect