jenkins_namespace: jenkins
jenkins_release_name: jenkins
jenkins_chart_version: "5.8.10"

nfs_server: "192.168.56.33"
nfs_path: "/srv/nfs/k8s/jenkins"

jenkins_admin_user: "admin"
jenkins_admin_password: "Admin1234!"

jenkins_node_port: 32000

nexus_admin_username: "admin"
nexus_admin_password: "admin1234"
nexus_host: 192.168.56.33
nexus_docker_port: 8082